name: 'the_tuva_project_demo'
version: '0.1.9'
config-version: 2

profile: 'color_tuva_profile'

vars:

  claims_enabled: true
  clinical_enabled: true
  provider_attribution_enabled: true

  ## CMS HCC data mart vars
  # Setting the payment year to year needed for the demo data
  cms_hcc_payment_year: 2018

  ## Quality Measure data mart vars
  # Setting the reporting period to date needed for demo data
  quality_measures_period_end: "2018-12-31"

  oncology_icd10_prefix: 'C'
  min_high_spend_threshold: 50000
  'dbt_date:time_zone': 'America/Los_Angeles'
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
# Specific Configuration for Models
models:
  color_oncology_exploration:
    # 1. Staging: Standardizing the 13 Tuva source tables
    # These are views to save storage and ensure we always pull the latest data.
    staging:
      +materialized: view
      +schema: staging
    
      
    # 2. Intermediate: The "Joining Engine" 
    # These contain the complex logic for Cohort IDs and Cost Profiling.
    intermediate:
      +materialized: view
      +schema: intermediate
      

    # 3. Marts: The final tables for the CEO dashboard
    # These are materialized as tables for faster performance in BI tools.
    marts:
      +materialized: table
      +schema: marts
    



tests:
  +store_failures: true 

seeds:
  the_tuva_project_demo:
    appointment:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.15.0','appointment.csv',headers=true) }}"
    eligibility:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.15.0','eligibility.csv',headers=true) }}"
    immunization:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.15.0','immunization.csv',headers=true) }}"
    lab_result:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.15.0','lab_result.csv',headers=true) }}"
    medical_claim:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.15.0','medical_claim.csv',headers=true) }}"
    observation:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.15.0','observation.csv',headers=true) }}"
    pharmacy_claim:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.15.0','pharmacy_claim.csv',headers=true) }}"
    provider_attribution:
      +post-hook: "{{ the_tuva_project.load_seed('tuva-public-resources/versioned_tuva_synthetic_data/0.15.0','provider_attribution.csv',headers=true) }}"
